baseURL: https://aigeoo.github.io/
languageCode: ar
title: Ù…Ø¯ÙˆÙ†Ø© ÙŠÙˆØ³Ù
theme: mini

defaultContentLanguage: ar

hasCJKLanguage: true
permalinks:
  posts: /posts/:slug/

paginate: 7

markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true

social:
  github: https://github.com/aigeoo
  twitter: https://twitter.com/aigeo_

params:
  author: ÙŠÙˆØ³Ù
  bio: Ù…Ø®ØªØ±Ù‚, Ù…Ø·ÙˆØ±, Ø·Ø§Ù„Ø¨ Ø¹Ù„Ù…
  description: A specialized blog bridging cybersecurity and programming expertise
  showToc: true
  showPowerBy: false
  math: false
  enableTwitterCard: true
  enableShare: true
  hiddenPostSummaryInHomePage: true
  copyright: 'Â© Ø­Ù‚ÙˆÙ‚ Ø§Ù„Ù†Ø´Ø± Ù…Ø­ÙÙˆØ¸Ø© ğŸ•¸ 2024'
